### ISSUE TITLE
dict constructor/syntax incompatibility between jython and cpython 2

### ISSUE THREAD

**Issue by jiqingtanguc** [jython/jython#11]
In Jython:

>>> dict({}, **{object(): 1})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: type keywords must be strings

In CPython:

In [31]: dict({}, **{object(): 1})
Out[31]: {<object at 0x1097dca10>: 1}

**Comment by jeff5** [comment]
This is interesting because it is a consequence of the way Jython calls methods. If there is a `**` argument, then it is assumed to be a keyword dictionary, therefore to have string keys. I think it would be difficult (probably impossible) to change this as it is in the generic part of the call process, rather than embedded in the implementation method.

The documentation for [calls](https://docs.python.org/2.7/reference/expressions.html#calls) says "If the syntax `**expression` appears in the function call, expression must evaluate to a mapping, the contents of which are treated as additional keyword arguments." Clearly a keyword is representable as a string and Jython takes advantage of this fact in its call mechanism.

The problem is that CPython 2 doesn't always check that they are keywords. In this case, Python 3 does check:
```
dict({}, **{object(): 1})
Traceback (most recent call last):
  File "<pyshell#97>", line 1, in <module>
    dict({}, **{object(): 1})
TypeError: keywords must be strings
```
