### ISSUE TITLE
Launch fails on Mac OS Big Sur (MacOS 11)

### ISSUE THREAD

**Issue by aforsythe** [jython/jython#125]
I'm currently having an issue with Jython on Mac OS 11.

I get the following error:
`The operation couldn’t be completed. Unable to locate a Java Runtime that supports -Xmx512m`

I've installed with Homebrew using:
`brew install jython`

It installs from a bottle apparently built for Catalina.

I've also tried installing using:
`brew install jython --build-from-source `

Same error at runtime

**Comment by speedyconzales** [comment]
Same issue here. Literally. Also installed via homebrew. I am on macOS 11.5.2. Was hoping to find an answer here. I am curious what java version to use with jython.

**Comment by aforsythe** [comment]
currently I'm using 

```
openjdk 11.0.11 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)
```

**Comment by Stewori** [comment]
I suppose you tried to launch Jython using the command ``jython``. For some reason, it appears Java stopped supporting the `Xmx` option which is used by the launcher. A possible workaround may be to launch it "manually" using the ``java`` command, e.g. like so:
```
java -jar please_figure_out_the_path/jython.jar
```
Please report back whether that works.

**Comment by aforsythe** [comment]
`java -jar /usr/local/Cellar/jython/2.7.2/bin/jython` 
produces
`Error: Invalid or corrupt jarfile /usr/local/Cellar/jython/2.7.2/bin/jython`

**Comment by Stewori** [comment]
Please try
```
java -jar /usr/local/Cellar/jython/2.7.2/jython.jar
```

**Comment by aforsythe** [comment]
```
java -jar /usr/local/Cellar/jython/2.7.2/jython.jar
Error: Unable to access jarfile /usr/local/Cellar/jython/2.7.2/jython.jar
```

`jython.jar` does not exist in that location.  Nor in `/usr/local/Cellar/jython/2.7.2/bin`

In `/usr/local/Cellar/jython/2.7.2/bin` there is one file name `jython` which is a symlink to `/usr/local/Cellar/jython/2.7.2/libexec/bin/jython`

`jython.jar` is in `/usr/local/Cellar/jython/2.7.2/libexec`

Running `java -jar /usr/local/Cellar/jython/2.7.2/libexec/jython.jar` brings up the Jython command line.

Not sure how to use that in my IntellJ IDE

**Comment by aforsythe** [comment]
Not sure if this is relevant but `/usr/local/Cellar/jython/2.7.2/libexec/bin/jython` is a python script that says it's a launcher.

running `jython --print` produces 

`java -Xmx512m -Xss2560k -classpath ../libexec/jython.jar:. -Dpython.home=../libexec -Dpython.executable=../libexec/bin/jython -Dpython.launcher.uname=darwin -Dpython.launcher.tty=true -Dfile.encoding=UTF-8 org.python.util.jython`

running that command brings up the jython command line even though `-Xmx512m` is included

**Comment by Stewori** [comment]
> Running `java -jar /usr/local/Cellar/jython/2.7.2/libexec/jython.jar` brings up the Jython command line.

That's good; so the problem is "solved" by removing the memory option.

> running that command brings up the jython command line even though `-Xmx512m` is included

Interesting. So what command is it then that causes trouble (I assumed plainly `jython`)? What happens if you plainly run `jython`? Is the command line Java the same that IntellJ uses?

**Comment by aforsythe** [comment]
> That's good; so the problem is "solved" by removing the memory option.

`java -jar /usr/local/Cellar/jython/2.7.2/libexec/jython.jar` brings up the jython command line

`java -Xmx512m -Xss2560k -classpath ../libexec/jython.jar:. -Dpython.home=../libexec -Dpython.executable=../libexec/bin/jython -Dpython.launcher.uname=darwin -Dpython.launcher.tty=true -Dfile.encoding=UTF-8 org.python.util.jython` brings up jython the command line

`jython` alone yeilds `The operation couldn’t be completed. Unable to locate a Java Runtime that supports -Xmx512m.
Please visit http://www.java.com for information on installing Java.`

> Is the command line Java the same that IntellJ uses?

I believe so.  When trying to setup my project to use Jython, I need to setup Jython as an available "Python SDK".  It does not let me choose a `.jar` file and only let's me choose the `jython` script.  Using the `jython` script as the Python SDK path yeilds the error ` The operation couldn’t be completed. Unable to locate a Java Runtime that supports -Xmx512m`

**Comment by Stewori** [comment]
Can you open the launcher `jython.py` with write access?
Can you change this part
```
    @property
    def java_opts(self):
        return [self.java_mem, self.java_stack]
```
into
```
    @property
    def java_opts(self):
        return [self.java_stack]
```
i.e. remove `self.java_mem` from the list? That *should* solve it (for you). If it does, we can reason on how to make it a proper fix.

**Comment by aforsythe** [comment]
> i.e. remove self.java_mem from the list? That should solve it (for you). If it does, we can reason on how to make it a proper fix.

fixed the `-Xmx` but now complaining about `-Xss`

```
The operation couldn’t be completed. Unable to locate a Java Runtime that supports -Xss2560k.
Please visit http://www.java.com for information on installing Java.
```

**Comment by aforsythe** [comment]
There's something more serious going on here ... 

I tried commenting out line [344](https://github.com/jython/jython/blob/0a58cc26566d2b2334e80b2b3f2f42f6c738db2d/src/shell/jython.py#L344) to get rid of the `Unable to locate a Java Runtime that supports -Xss2560k.` errror.

That resulted in 

```
The operation couldn’t be completed. Unable to locate a Java Runtime that supports -classpath.
Please visit http://www.java.com for information on installing Java.
```

So I commented out line [354](https://github.com/jython/jython/blob/0a58cc26566d2b2334e80b2b3f2f42f6c738db2d/src/shell/jython.py#L354)

That resulted in 

```
The operation couldn’t be completed. Unable to locate a Java Runtime that supports -Dpython.home=...
Please visit http://www.java.com for information on installing Java.
```

**Comment by Stewori** [comment]
It does not seem to find Java at all. This error bothers other people too: https://superuser.com/questions/1636321/how-to-solve-unable-to-locate-a-java-runtime-that-supports-error (unfortunately no proper solution there as of this writing). You may want to check the environment variables `java -version`, `echo $JAVA_HOME` and `echo $JDKHOME` as it is written there, maybe it gives some clue.

That looks like it might not really be a Jython issue. Still it's good to collect information here, e.g. to implement a workaround in jython.py.

**Comment by aforsythe** [comment]
```
$  java -version
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)
```

Environment variables were not previously set ... 
Setting JAVA_HOME yields a strange result.

```
$  which java
/usr/bin/java

$ export JAVA_HOME="/usr/bin"

$  echo $JAVA_HOME
/usr/bin/

$ jython
Failed to launch Jython using command: /usr/bin/bin/java ...
    Use the --print option to see the command in full.
    Launcher used JAVA_HOME = /usr/bin
[Errno 2] No such file or directory

$ jython --print
/usr/bin/bin/java -Xss2560k -classpath /usr/local/Cellar/jython/2.7.2/libexec/jython.jar:. -Dpython.home=/usr/local/Cellar/jython/2.7.2/libexec -Dpython.executable=/usr/local/Cellar/jython/2.7.2/libexec/bin/jython -Dpython.launcher.uname=darwin -Dpython.launcher.tty=true -Dfile.encoding=UTF-8 org.python.util.jython

$ export JAVA_HOME="/usr"

$  jython
The operation couldn’t be completed. Unable to locate a Java Runtime that supports -Xss2560k.
Please visit http://www.java.com for information on installing Java.
```

**Comment by aforsythe** [comment]
I think I fixed it. 

The issue appears to indeed be related to the `JAVA_HOME` environment variable.

To set it correctly use : 

`export JAVA_HOME=$(/usr/libexec/java_home)`

There's another issue related to MacOS Big Sur discussed [here](https://github.com/hardwarelayer/tientn-jboard-game/issues/3)

Doing the following solves that issue
```
sudo ln -s /usr/local/opt/openjdk/libexec/openjdk.jdk/Contents/Home/lib/server/libjvm.dylib /usr/local/opt/openjdk/libexec/openjdk.jdk/Contents/Home/lib/libjvm.dylib
```

**Comment by jeff5** [comment]
Thanks for solving this puzzle. I'm relieved that Java hasn't suddenly decided not to support the `-Xmx` option. That's a dreadfully misleading error message.

I always have `JAVA_HOME` set because it's part of my home-made JDK (and Python) switcher. In various circumstances though, I can find I have a surprising environment in a sub-shell (e.g. finding the system Python in a Gradle `Exec` task). It seems like there's an element of that here.

I think the summary is:

> The launcher will invoke Java in a sub-shell that may look for a system-defined JDK, rather than the one current in your environment, and that JDK may be wrong, missing or broken. A solution is to define the exact JDK via JAVA_HOME, which the launcher will use explicitly.

**Comment by Stewori** [comment]
@jeff5 or @aforsythe , does one of you understand how this issue relates to MacOS 11, i.e. is it "systematic"? Was the default Java location changed? I am asking because in that case the launcher should be updated to look for a jdk in `/usr/libexec/java_home` as another fallback in case no workable `JAVA_HOME` is provided.
I mean, in that case "that JDK may be wrong, missing or broken" would not really apply but the way how the launcher locates it would be flawed. Fixing this in the launcher might be the only way to prevent "masses" of further users running into this issue.

**Comment by aforsythe** [comment]
I don't know how this relates to MacOS 11 specifically but it's worth noting this isn't as straight forward as it might seem.
If you set the environment variable with

```
export JAVA_HOME=$(/usr/libexec/java_home)
```

You get

``` 
$  echo $JAVA_HOME
/usr/local/Cellar/openjdk/16.0.2/libexec/openjdk.jdk/Contents/Home
```
oh, and yes I moved to `16.0.2`from `11.0.11` in the process here but I don't believe that actually had anything to do with fixing the issue.  `/usr/libexec/java_home` appears to be a Mac OS specific file (yes `java_home` is a file) that redirects you to whatever the correct `JAVA_HOME` is.

**Comment by aforsythe** [comment]
Just to button this up ... 
To get `jython` to work on MacOS 11 (Big Sur 11.5.2) I did
```
brew install openjdk
brew install jython
echo 'export PATH="/usr/local/opt/openjdk/bin:$PATH"' >> ~/.zshrc
echo 'export JAVA_HOME=$(/usr/libexec/java_home)' >> ~/.zshrc
```

Lots of work to figure out a few commands

**Comment by Stewori** [comment]
Maybe this is not about OSX 11 but actually about brew-installed Java...
You don't have the oportunity to check whether the `/usr/libexec/java_home` symlink was present before OSX 11 (or before installing Java via brew maybe), do you?
Anyway, I guess the launcher should check for presence of a `/usr/libexec/java_home` symlink as a fallback on OSX if no `JAVA_HOME` is set. @jeff5 what do you think? @jimbaker IIRC you were also on OSX. Do you have a `/usr/libexec/java_home` on your system?

**Comment by aforsythe** [comment]
I don't think it is due to homebrew installed Java.  I tried using the installer at one point thinking that may be the issue but it didn't solve the problem.  Also, /usr/libexec/java_home doesn't appear to be a symlink. I'm not currently in front of my computer but I'll investigate more when I have a chance.

**Comment by jeff5** [comment]
`$(whatever)` means run `whatever` and take stdout as the value (doesn't it?), so `/usr/libexec/java_home` is a script that does some magic to give you a value to assign to `JAVA_HOME`.

This magic appears to be [a bit fragile](https://developer.apple.com/forums/thread/666681).

Rather than hide a use of this magic inside our own (the launcher), it seems safer for it be explicitly performed by the user. We could give a hint about `JAVA_HOME` not being set, if we can detect that it failed, or perhaps unconditionally (although not in a way that pollutes output when Jython itself is used in a script).

Also, Apple-specific features are difficult (for me) to test.

I think the root of the problem, and it is not specific to platform, is that the environment in which Jython runs as a sub-process is not quite the same as it is at the prompt. I don't know why.

By Alexander's report:

> Running `java -jar /usr/local/Cellar/jython/2.7.2/libexec/jython.jar` brings up the Jython command line.

and so does the longer one `java -Xmx512m -Xss2560k ... org.python.util.jython`

And yet it appears that the same command issued through `subprocess.call` or `os.execvp`  finds a meaning for `java` that produces a misleading error message. This defective fall-back `java` runs successfully, as far as return status goes. (It's worth remembering this is within CPython, in the launcher, not our hacked-about `subprocess.py`.)

As I understand it,  `subprocess.call` and `os.execvp` should give the sub-process the same environment the launcher itself sees, and use the same path to find `java`.

**Comment by Stewori** [comment]
Maybe `which java` is the key to make the launcher *actually* use the java from the prompt.
@aforsythe could you please check if
```
python -c "import subprocess; subprocess.call('which java', shell=True)"
```
does really yield the same result as plainly calling `which java`?
Then the launcher could use the result of `subprocess.call('which java', shell=True)` as a fallback for missing `JAVA_HOME`. Hopefully, this would circumvent the issue explained by Jeff, i.e. "that the environment in which Jython runs as a sub-process is not quite the same as it is at the prompt."

Edit: Okay, from an earlier post it is evident that `which java` is not suitable to determine the location of java. It yields `usr/bin/java` instead of the "true" `/usr/local/Cellar/openjdk/16.0.2/libexec/openjdk.jdk/Contents/Home/bin/java`. Difficult.

Edit2: What about `readlink -f /usr/bin/java`? Does it work on OSX? Looks promising on my Linux machine. So finally we may want to use something similar to
```
python -c "import subprocess; subprocess.call('readlink -f $(which java)', shell=True)"
```

**Comment by aforsythe** [comment]
`python -c "import subprocess; subprocess.call('which java', shell=True)"` and `which java` are now both pointing to
`/usr/local/opt/openjdk/bin/java`

I think this is due to my setting `echo 'export PATH="/usr/local/opt/openjdk/bin:$PATH"' >> ~/.zshrc` which was not previously set. 

`readlink /usr/bin/java` results in no output. (`-f` isn't a legal option on MacOS 11)

**Comment by aforsythe** [comment]
>  Also, /usr/libexec/java_home doesn't appear to be a symlink.

Just to circle back to this.  `/usr/libexec/java_home` is a binary file

**Comment by Stewori** [comment]
> ``-f`` isn't a legal option on MacOS 11

Too bad :(
Please try
```
python -c "from pathlib import Path; print(Path('/usr/bin/java').resolve())"
```

**Comment by aforsythe** [comment]
```
$  python -c "from pathlib import Path; print(Path('/usr/bin/java').resolve())"
/usr/bin/java
```

**Comment by Stewori** [comment]
Okay. I used to think that `usr/bin/java` is a symlink to the actual java home in sense of `java_home/bin/java`. So, either `resolve` does not work properly or on some systems `usr/bin/java` is indeed the actual Java binary rather than a symlink (strange... I believe the `java` command needs some environment with libs etc, which is why `usr/bin/java` uses to be a symlink. Unfortunately, I don't have access to a mac to figure things out). In the symlink case we could have used `dir_of_result_of_resolve_/..` to identify the actual Java home (since evidently plain `usr/bin/java` is not good enough for some reason).

Now, as far as I can assess it, the only way to improve the launcher is to consider the result of calling `/usr/libexec/java_home` as one more fallback on OSX; not taking it's validity for granted though (as @jeff5 pointed out). However, I am not sure if we would want to do this; there was once a security issue with calling `cmd` on windows because some attacker could possibly replace `cmd` by an arbitrary malicious command. Could this happen to `/usr/libexec/java_home` too? (But then why aren't we concerned about the `java` command itself?) So, I would believe that if an attacker is able to override system commands, the fight is already lost. So the launcher could call `/usr/libexec/java_home` as a fallback. Opinions? Ideas? Preferences?

**Comment by Stewori** [comment]
Okay, the security issue I referred to is https://bugs.jython.org/issue2882. I did not remember it in detail. The actual issue was that `cmd` was called without full path, so it could be overridden in the current working directory. So it shouldn't be an issue if we call full-path `/usr/libexec/java_home` in the launcher.

**Comment by jeff5** [comment]
It turns out I needed to know this. :)

I've been delving into MacOS a bit through the keyhole that is Travis CI. I'm trying to run Jython on Java 8, so it isn't quite the same, and Travis wants you to supply YAML to their add-on rather than run actual `brew` commands, but much of the pain is from the same phenomenon Alexander starts with.

We install `openjdk@8` via the homebrew add on. What I learn from many hours of trial-and-error, research, and reading logs is that `brew` does not link (some?) installed JDKs into the directory where the JDK switcher `/usr/libexec/java_home` can find them. You have to do that yourself.

So after the `brew` stuff, we use:
```
sudo ln -sfn $(brew --prefix)/opt/openjdk@8/libexec/openjdk.jdk   /Library/Java/JavaVirtualMachines/openjdk-8.jdk
export JAVA_HOME="$(/usr/libexec/java_home -v1.8)"
export PATH="$JAVA_HOME/bin:$PATH"
```
Only then does the build complete with the right JDK.

**Comment by Stewori** [comment]
Would it make sense to build some brew-awareness into the launcher? The launcher could additionally check for typical brew jdk install locations (as a fallback). brew is an widely used system on OSX afterall.

**Comment by jeff5** [comment]
@Stewori : Hunting for JDK installations the user has not put on their path sounds like it could have unexpected consequences. `brew` claims it does what seems to be an [unfinished job](https://docs.brew.sh/Querying-Brew#linked-keg-only-formulae) because linking the JDK where we'd expect creates conflicts and we'd be reversing that.

However, it does [tell you what to do](https://formulae.brew.sh/formula/openjdk@8) if you want the system Java wrappers to find the JDK.

An installer (or application) that brings its own JVM sounds a better answer (in 3?). Or just a pointer to brew's advice.

**Comment by bts-webber** [comment]
Same issue here,but I solved it.
Modify `jython` in line 578
From `os.execvp(command[0], command[1:])` 
To `os.system(' '.join(command))`

**Comment by mitchblank** [comment]
Could you just try `os.execvp(command[0], command)`?

The second argument to `execvp` is supposed to include the full list of arguments *including* `argv[0]`!

**Comment by jeff5** [comment]
> Could you just try `os.execvp(command[0], command)`?
> 
> The second argument to `execvp` is supposed to include the full list of arguments _including_ `argv[0]`!

That's really helpful, thanks @mitchblank . It's surprising such a mistake doesn't have a more serious effect on Linux platforms, although maybe this is because few people use `jython.py` in place of `jython` the shell script. (I'm not skilled enough with shell scripts to maintain the latter, and the former is supported mainly as a basis for the launcher on Windows.)

The effect is to ignore the first option "-Xmx512m". I've proved this by inserting a manifestly invalid option at `command[1]`, on Linux. The problem originally reported is not I think _caused_ by this, but by `brew` weirdness. However, if it is picking up the name from `argv[0]`, it perhaps explains why the message it gives is confusing:
```
The operation couldn’t be completed. Unable to locate a Java Runtime that supports -Xmx512m
```
But it may be the cause. So I'll fix this for the beta. I believe I can test it on a MacOS with a GitHub action but user feedback would be welcome.

**Comment by jeff5** [comment]
A better way of probing this lost argument problem (this from a GitHub action running on MacOS 11):
```
dist/bin/jython -c 'from java.lang.management import ManagementFactory; print ManagementFactory.getRuntimeMXBean().getInputArguments()'
[-Xmx512m, -Xss2560k, -Dfile.encoding=UTF-8, -Dpython.home=dist, -Dpython.executable=dist/bin/jython]
```
Then explicitly invoking this via the Python script we can see what's missing:
```
python2 dist/bin/jython.py -c 'from java.lang.management import ManagementFactory; print ManagementFactory.getRuntimeMXBean().getInputArguments()'
[-Xss2560k, -Dpython.home=dist, -Dpython.executable=dist/bin/jython.py, -Dpython.launcher.uname=darwin, -Dpython.launcher.tty=false, -Dfile.encoding=UTF-8]
```

Writing the GitHub action did not present the same difficulties as on TravisCI where `brew` is used. In fact, it worked first time.

**Comment by jeff5** [comment]
I'm 90% sure that last commit fixes this, but the tests I can run via GitHub actions do not involve a JDK installed by `homebrew`.

Jython definitely runs on MacOS 11, however. Closing for now.
