### ISSUE TITLE
jython compile 

### ISSUE THREAD

**Issue by niuzhi** [jython/jython#142]
hi
I use gradlew build to compile the master branch of the jython project. When compiling pycompiler, it always prompts java.lang.ExceptionInInitializerError. How can I solve it?
![image](https://user-images.githubusercontent.com/33443724/142625085-c2b65217-ac47-4dbd-bbdc-f84b76bee065.png)

![image](https://user-images.githubusercontent.com/33443724/142625266-d16b15aa-ca6d-40ad-b8c0-5f00989be97c.png)

**Comment by jeff5** [comment]
Does running Gradle with any of the suggested options tell you more?

If I remember correctly, even with a (Java) stack trace, exceptions in initialisation make it hard to get to the root cause.

I think the relevant version of Ant will be the one in the dependencies section. (I hope it's not satisfying some Ant dependency from my environment.)
