### ISSUE TITLE
Comparison of Unicode strings

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [jython/jython#144]
This is a regression:

```
Jython 2.7.2 (v2.7.2:925a3cc3b49d, Mar 21 2020, 10:03:58)
[OpenJDK 64-Bit Server VM (Red Hat, Inc.)] on java11.0.11
Type "help", "copyright", "credits" or "license" for more information.
>>> u'caña' == 'caña'
False

>>> u'cana' == 'cana'
True

```
Comparison between u-Strings and regular Strings fails when we use non-English characters.

Jython 2.7.1 used to work well.

**Comment by jeff5** [comment]
More importantly, it works in Python 2.

I blame this fellah 197db79cf7ea1be0228ed9952022b8d60337cdcf . Evidently I believe that a default decoding (which is ASCII) should be applied, which is wrong I agree..

**Comment by DavidPerezIngeniero** [comment]
This is the behaviour of CPython:

```
$ python
Python 2.7.18 (default, Aug 27 2020, 21:22:52) 
[GCC 7.3.1 20180712 (Red Hat 7.3.1-9)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> u'caña' == 'caña'
__main__:1: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
False

>>> u'cana' == 'cana'
True
```

**Comment by jeff5** [comment]
What you get from CPython depends on how your terminal is set up. When I type what you (@DavidPerezIngeniero) type in my terminal, evidently it doesn't read what I appear to have typed:
```
PS Python2> python
Python 2.7.18 (v2.7.18:8d21aa21f2, Apr 20 2020, 13:25:05) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.stdin.encoding
'cp936'
>>> u'caña' == 'caña'
True
>>> map(ord, 'caña')
[99, 97, 63, 97]
```
I think behaviour may have changed here, either of Windows PoSH or CPython, since I last looked.

I'll investigate. But what are the bytes in 'caña' where you type it?

**Comment by jeff5** [comment]
Ok, investigating this with a console where I can actually type an ñ, CPython behaviour is indeed:
```
PS Python2> python
Python 2.7.18 (v2.7.18:8d21aa21f2, Apr 20 2020, 13:25:05) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.stdin.encoding
'cp1252'
>>> u'caña' == 'caña'
__main__:1: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal

False
>>> map(ord, 'caña')
[99, 97, 241, 97]
```
Evidently from my earlier post, this was not what I observed in CPython the first time, but I think that was because in both contexts ñ was quietly replaced by ?.

And Jython 2.7.2 behaviour is:
```
PS Jython> jython
Jython 2.7.2 (v2.7.2:925a3cc3b49d, Mar 21 2020, 10:03:58)
[Java HotSpot(TM) 64-Bit Server VM (Oracle Corporation)] on java1.8.0_321
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.stdin.encoding
'cp1252'
>>> u'caña' == 'caña'
False
>>> map(ord, 'caña')
[99, 97, 241, 97]
```

Unicode and bytes are not really comparable, but Python 2 cuts you some slack. Once on that slippery slope, there isn't exactly a right answer. Jython 2.7.2 is giving the same answer as CPython, which we always prefer in disputable cases. (Ok, same apart from the `UnicodeWarning`.) Jython 2.7.1 is wrong by that standard.

**Comment by DavidPerezIngeniero** [comment]
The problem arises with any non-English letter.
'ñ' is unicode char '\uF1º.

```
>>> '\xf1'=='ñ'
False
>>> u'\xf1'==u'ñ'
True
```

**Comment by jeff5** [comment]
> The problem arises with any non-English letter. 'ñ' is unicode char '\uF1'.
> 
> ```
> >>> '\xf1'=='ñ'
> False
> ```

Yes, but this is not a problem with Jython v2.7.2, since you will get the same result from a recent CPython. (It used to be a problem in v2.7.1 that they differed, a relic of UTF-16 `str`, but we fixed that.) On Linux, with a UTF-8 console, which you probably have, `'ñ'` spells `'\xc3\xb1'`. You see what a leap it would be to have that equal `'\xf1'`?

Python 2 will let you compare `unicode` and `str` using the default decoding of the `str`. The default decoding is ASCII because most encodings agree in that range. It's still a leap. You should know the encoding by which the bytes represent characters and you could either decode them for the comparison, or compare with the encoded version of your candidate.
