### ISSUE TITLE
Jsr223 and jython-standalone performance issue

### ISSUE THREAD

**Issue by nevcx** [jython/jython#152]
I have a application that combines python and java, like Flask among others.
The script files can be trusted and are loaded dynamically.

If I revert the following commit https://github.com/jython/jython/commit/939c8d415fd011ccda249348445f89f471a41567 on head, the performance increases many times over.

The performance issue can be illustrated by the following code.

```
import javax.script.*;

class Jsr223 {
    public static void eval() throws ScriptException {
        ScriptEngineManager factory = new ScriptEngineManager();
        ScriptEngine engine = factory.getEngineByName("python");
        engine.eval("print '.',");
    }

    public static void main(String[] args) throws ScriptException {
        for (int c = 0; c < 25; c++) {
            eval();
        }
    }
}
```

Is there any way to get around this?
My goal is to be able to upgrade from v2.7.0 to v2.7.2.

Many thanks!

**Comment by jeff5** [comment]
It depends on your application, but an obvious strategy is to create an interpreter and continually re-use it. It has to be cleaned between uses, of course.

The isolated state is an attempt to serve multiple threads with an interpreter each. If your use is serial, as here, then one interpreter may be re-used. If your application is multi-threaded, maybe a pool of them can be created.

Another possibility is to create a `PythonInterpreter` directly, not using JSR 223. By default, all such interpreters re-use the same `PySystemState` (`sys` module), although you can choose otherwise.
