### ISSUE TITLE
exec result error

### ISSUE THREAD

**Issue by kt10001** [jython/jython#186]
expression: result = '企业法人' in ['个体工商户','公司股东',]  result: true
It should be false.

my code

```java
public class ExpressionCalculateUtil {

    /**
     * python 字符串表达式计算
     * 格式
     *  result = 1000 >= 2000
     *  result = 'A' in ['A','B','C','D','M',]
     * @param expression
     * @return
     */
    public static Boolean boolExpression(String expression) {
       PythonInterpreter pyInterpreter = new PythonInterpreter();
        pyInterpreter.exec(expression);
        boolean result = "True".equals(pyInterpreter.get("result").toString());
        System.out.println("expression: " + expression + " result: " + result);
        return result;
    }

    public static void main(String[] args) {
        boolExpression("result = '企业法人' in ['个体工商户','公司股东',]");
    }
}
```

maven
```
<dependency>
	<groupId>org.python</groupId>
	<artifactId>jython-standalone</artifactId>
	<version>2.7.0</version>
</dependency>
```

**Comment by jeff5** [comment]
The Java interface to the interpreter is not good with anything but ASCII (maybe Latin-1) due to some deeply-embedded implementation choices. Quite likely it thinks you said `'????' in ['?????','????',]`, which is `True` of course. There seems to be no easy work-around for this and the complexity of what lies behind the API has stalled a fix.

As a file, this works for me:
```
# -*- coding: utf-8 -*-

print '企业法人'
print '企业法人' in ['个体工商户','公司股东']

print u'企业法人'
print u'企业法人' in [u'个体工商户', u'公司股东']

print u'企业法人' in [u'个体工商户', u'企业法人']
```
and I get:
```
PS 186> jython inlist.py
浼佷笟娉曚汉
False
企业法人
False
True
```
The first line looks wrong, but it is just the effect of utf-8 bytes seen through my cp936 terminal.  Note the Python 2 use of u-prefix to `unicode` literals.)

If it is not too annoying, representing characters `>0x7f` as their `\uxxxx` equivalents should work:
```
Jython 2.7.0 (default:9987c746f838, Apr 29 2015, 02:25:11)
[Java HotSpot(TM) 64-Bit Server VM (Oracle Corporation)] on java1.8.0_321
Type "help", "copyright", "credits" or "license" for more information.
>>> u'\u4f01\u4e1a\u6cd5\u4eba' in [u'\u4e2a\u4f53\u5de5\u5546\u6237', u'\u516c\u53f8\u80a1\u4e1c']
False
>>> print u"u'\u4f01\u4e1a\u6cd5\u4eba' in [u'\u4e2a\u4f53\u5de5\u5546\u6237', u'\u516c\u53f8\u80a1\u4e1c']"
u'企业法人' in [u'个体工商户', u'公司股东']
```

Versions before 2.7.1 were generally poor with non-ASCII text. Since then we have put a lot of work into supporting Unicode properly **in code**. If we can get around the difficulty with the API, you'll find 2.7.2 less buggy in its dealings with Unicode. (The `jython-slim` JAR might also be a better choice of dependency.)

**Comment by kt10001** [comment]
Thank you for your reply.

Now, i known why.

So that, i will have idea to slove it
