### ISSUE TITLE
jython for python3.8

### ISSUE THREAD

**Issue by adrian-rt** [jython/jython#198]
Hi,

what if I want to call python 3.8 from Java?

I have a java application which uses jython 2.7.2 and It calls into python2.7 but I really need it to call python3.8 in order to load a custom python module which I created for this (3.8).

Are you planning on releasing a new update for this? or do you have any alternatives?

Many thanks!

**Comment by jeff5** [comment]
We're working towards exactly a [Jython 3.8](https://www.jython.org/jython-3-roadmap) but it would be wrong to give you a date.

If it would work for you to use CPython externally, then that can be launched as a sub-process, but that's not a Jython question. You can't then use Java classes in it.

We call your CPython to compile modules too large for Java, but it has to be a 2.7 in that context.

**Comment by adrian-rt** [comment]
will it be possible in Jython 3.8 to import Python modules written in C?

As I understand in Jython 2.7 you can only import pure python modules :(

thanks.

**Comment by jeff5** [comment]
It's not an early objective.

An extension like JyNI may be possible but is very difficult. There are also developments in CPython that change the game, but for better or worse I can't say. Perhaps when Jython 3 is a roaring success, @Stewori will show us how it's done.

The problem is not integration of C with Java as such, which is certainly possible, but integration of code, generated by CPython's macros/inlines, that expects to find a very specific kind of memory layout, different from Java's.
