### ISSUE TITLE
Build failures on riscv64 openEuler OS

### ISSUE THREAD

**Issue by yinxx** [jython/jython#218]
[ 3380s] pycompile:
[ 3392s] [jycompile] Compiling 643 files
[ 3399s] [jycompile]   File "/home/abuild/rpmbuild/BUILD/jython-2.7.1/dist/Lib/encodings/gb18030.py", line 10
[ 3399s] [jycompile]     codec = _codecs_cn.getcodec('gb18030')
[ 3399s] [jycompile]          ^
[ 3399s] [jycompile] SyntaxError: no viable alternative at input '='
[ 3399s] [jycompile] Could not compile /home/abuild/rpmbuild/BUILD/jython-2.7.1/dist/Lib/encodings/gb18030.py

https://build.tarsier-infra.com/package/live_build_log/home:yinxx:jython/jython/openEuler_2209_self/riscv64

Any help is appreciated

**Comment by jeff5** [comment]
This isn't a platform we've tested on, but we aim to run where Java runs.

This last bit, where it finally dies, is probably not a clue to the root cause.

Looking at your log file, there are a lot of warnings that should be clues. The ANTLR part of the build is always fairly noisy, but this is worse than usual. I think the compiler you get from it is badly broken. The particular statement on which it gives up is clearly valid, and has worked thousands of times for others.

Going back further in the log, I can see that you are modifying our distribution quite heavily before you run the compilation, including deleting JARs and patching our source before you compile it, There should be no need for that and is outside what we can help with.

It looks like you are trying to work around some deprecation of `CharMatcher.ASCII`, which I think means you have somehow picked up later JARs (Guava isn't it?) than we provide.

I guess you are trying to get control over the versions of dependencies you run with.

There's a 2.7.3 version with later JARs we have tested with. It provides the usual builds  with shaded JARs, but also a `jython-slim` build without them. This should give you more control over the JARs you run with through manipulating dependencies in Maven or Gradle. You may need to do no more than name it in a Gradle or Maven build, or download it and put the JARs you trust on the class path.

**Comment by yinxx** [comment]
thanks so much
