### ISSUE TITLE
Any plan to support python3?

### ISSUE THREAD

**Issue by thaumstrial** [jython/jython#235]
Python2 is a bit out of date, are there any plans to upgrade to support python3

**Comment by Stewori** [comment]
https://github.com/jython/jython/issues/198
https://www.jython.org/jython-3-roadmap

**Comment by stuaxo** [comment]
Looks like a related question came up here https://github.com/jython/jython3/issues/46

**Comment by furuochen-dev** [comment]
> #198 https://www.jython.org/jython-3-roadmap

Is doing stuff like [Jython Continued](https://github.com/jython-continued/jython) allowed/suggested?

**Comment by Stewori** [comment]
It's not forbidden AFAIK if the license is followed. However, it is likely not helpful either. It may even be counter productive if it causes fragmentation. Getting Jython 3 right is very challenging and easily underestimated. Chances are that it ends up like [this earlier attempt](https://github.com/jython/jython3). Efforts to Jython 3 should be coordinated and combined rather than distributed or maybe even competing. If you are interested in developing Jython 3, consider to get into contact with @jeff5, learn about current status and how to help. Of course that's up to you, but core Jython could need more contributers.

**Comment by furuochen-dev** [comment]
> It's not forbidden AFAIK if the license is followed. However, it is likely not helpful either. It may even be counter productive if it causes fragmentation. Getting Jython 3 right is very challenging and easily underestimated. Chances are that it ends up like [this earlier attempt](https://github.com/jython/jython3). Efforts to Jython 3 should be coordinated and combined rather than distributed or maybe even competing. If you are interested in developing Jython 3, consider to get into contact with @jeff5, learn about current status and how to help. Of course that's up to you, but core Jython could need more contributors.

If we have succeeded, is distribution allowed?

**Comment by jeff5** [comment]
@RuochenFu21 Making a fork is clearly allowed. Making a PR is clearly allowed.

Distributing a product and calling it Jython would be problematic since the name is owned by the Python Software Foundation.

You're allowed to contribute. You would need to sign the PSF contributor agreement.

It was a lot of work to get here. There is plenty to do. I'm glad you want Jython 3 to exist.

The implementation approach in Jython3 is quite different because at the core of 2 is a workaround we no longer need in modern Java. I would have discouraged contribution a year ago (unless from long-term contributors who understand the risk), because I don't like leading people down the dead end it might have been. But it begins to look like the right track now.

- This is where I try things I'm not sure are right: https://github.com/jeff5/very-slow-jython
- This where I explain it: https://the-very-slow-jython-project.readthedocs.io/en/latest/ (Material before chapter 4 "A Plain Java Object Interpreter" is abandoned lines of development.)
- This is the real thing: https://github.com/jython/jython/tree/main  (Beware of old Jython 2 material retained for reference or porting.)

**Comment by Stewori** [comment]
> is distribution allowed?

As Jeff already pointed out, beyond fulfilling the license duties one has to obey trademark restrictions. For some further reading, once upon a time there was the thread [Someons's put a "Python 2.8" on GitHub](https://www.mail-archive.com/python-dev@python.org/msg94612.html) on python-dev.

> If we have succeeded

That sounds promisingly confident. May I kindly ask you to fill us in on your approach and its current state?

**Comment by furuochen-dev** [comment]
@Stewori @jeff5 Our team decided not to continue this project, as it's not very helpful as Stewori said, and might cause license problems, we decided to start a new project that might be similar to Jython but focused on different things _o_

**Comment by heeplr** [comment]
I suppose there's still no ETA for this?
Can you maybe give a rough hint? Something like "surely this year", "maybe next year", "probably in the next few years", "still not 100% sure if there ever will be a jython 3.x release" ... :smiley:

**Comment by jeff5** [comment]
> Can you maybe give a rough hint? Something like "surely this year", "maybe next year", "probably in the next few years", "still not 100% sure if there ever will be a jython 3.x release" ... 😃

Not the first option.
