### ISSUE TITLE
Jython 2.7.2 is not working

### ISSUE THREAD

**Issue by anasokan** [jython/jython#242]
Hi Team,

I am getting the below error in getSystemState() when using jython 2.7.2 but when using jython 2..7.1b3 it seems working.
What is changed here and what are the new dependencies?

```
Exception java.lang.NoSuchMethodError: jnr.ffi.Platform.getStandardCLibraryName()Ljava/lang/String;
jnr.posix.POSIXFactory.<clinit>(POSIXFactory.java:21)
org.python.modules.posix.PosixModule.<clinit>(PosixModule.java:85)
org.python.modules.Setup.<clinit>(Setup.java:68)
org.python.core.PySystemState.initBuiltins(PySystemState.java:1444)
org.python.core.PySystemState.doInitialize(PySystemState.java:1204)
org.python.core.PySystemState.initialize(PySystemState.java:1130)
org.python.core.PySystemState.initialize(PySystemState.java:1085)
org.python.core.PySystemState.initialize(PySystemState.java:1080)
org.python.core.PySystemState.initialize(PySystemState.java:1075)
org.python.core.PySystemState.initialize(PySystemState.java:1070)
org.python.core.ThreadStateMapping.getThreadState(ThreadStateMapping.java:56)
org.python.core.Py.getThreadState(Py.java:1741)
org.python.core.Py.getThreadState(Py.java:1737)
org.python.core.Py.getSystemState(Py.java:1757)
```

**Comment by Stewori** [comment]
There is not enough context to answer your question. Jython 2.7.2 generally works, passes tests etc. Including tests of the posix module.

- Given the stack trace I would guess that your setup contains for some reason a wrong jnr version. Did you try the standalone version of Jython? Can you check your classpath to find out which jnr version is used?
- What code snippet is causing this? It looks like initialization of the posix module. Is it caused readily by the import?

Finally I would recommend to check issues always with the latest release, i.e. Jython 2.7.3 or even better with the current github version. That avoids spending time on issues that might have been already fixed (maybe indirectly).

**Comment by jeff5** [comment]
Dependencies are conveniently read here: https://github.com/jython/jython/blob/8c3734d1f09d0e2de8843c3d8f22b469b83e6860/build.gradle#L134
or here: https://github.com/jython/jython/blob/8c3734d1f09d0e2de8843c3d8f22b469b83e6860/build.xml#L238

@anasokan : The fact that you're asking suggest you're rolling your own class path in some way?

@Stewori : from the trace I can see we're here: https://github.com/jython/jython/blob/8c3734d1f09d0e2de8843c3d8f22b469b83e6860/src/org/python/modules/posix/PosixModule.java#L85 but you're right to think the problem is not likely to be some change we made here, since it hasn't changed in a long time. It is a call that only happens once, normally, and in circumstances (interpreter startup) that we mostly control, making the OP's theory that it is change further down that is the problem.
