### ISSUE TITLE
Compilation error for 2.7.1

### ISSUE THREAD

**Issue by datavisortedyu** [jython/jython#244]
I am trying to compile v2.7.1 on Mac with java 8 by running `ant` command.
```
    [javac] /Users/zhihongyu/jython/src/org/python/core/PyStringMap.java:16: error: package org.python.core.PyMapSet does not exist
    [javac] import org.python.core.PyMapSet.PySetIter;
    [javac]                                ^
    [javac] /Users/zhihongyu/jython/src/org/python/core/PyStringMap.java:837: error: cannot find symbol
    [javac]         return new PyMapEntrySet(getMap().entrySet());
    [javac]                    ^
    [javac]   symbol:   class PyMapEntrySet
    [javac]   location: class PyStringMap
```
Can someone shed some light ?

Thanks

**Comment by Stewori** [comment]
Maybe an issue with the target...? (you see, I'd have to guess) Please post the whole command line you exec. That said, is there a reason why you compile 2.7.1 and not the current version?

**Comment by datavisortedyu** [comment]
The command is `ant`

We're using 2.7.1 now. I have a PR #243 for resolving deadlock, hence I chose to build 2.7.1

BTW please review #243, thanks

**Comment by Stewori** [comment]
I think there is no proper default target defined for ``ant`` in Jython (or it is broken). For a successful compilation you have to specify a  target explicitly, e.g. IIRC ``ant jython``, ``ant jython-standalone`` or ``ant jython-installer``. Use ``ant -p`` or if needed ``ant -p -v`` to get a list of all available targets (and to verify that I remembered the targets correctly - it has been a while since I actually ran a build).

> BTW please review https://github.com/jython/jython/pull/243, thanks

These days I am not an active Jython dev. I just help triaging issues. That being said, please note that no PR for Jython 2.7.1 would be accepted as there won't be a new Jython 2.7.1 release. No nano-version like Jython 2.7.1.1 would be introduced. The next release will be 2.7.4 and for PRs to be considered they have to work for 2.7.3 (for current github master, actually). Maybe your PR happens to work for 2.7.3 but you should better check that proactively.

I amend my recommendation for using Jython 2.7.3. Actually, as soon as you get into writing PRs you should use current github master, ``git clone https://github.com/jython/jython``.

**Comment by Stewori** [comment]
I noticed, the readme indeed tells you to just run ``ant``. I vaguely remember that this did not use to work for me when working on Jython 2.7.1. Maybe the default target has been fixed since then (or the readme has an issue there). Anyway, try specifying the target explicitly as I suggested above.

**Comment by jeff5** [comment]
The default target is the `developer-build`:
https://github.com/jython/jython/blob/4f68d98f34fd6165058944640925b0d1370caf4f/build.xml#L2
It compiles everything and makes a JAR only of our own code to save time, putting the bundled JARs on the path instead.

Clearly PyMapSet exists, although not in its own source file:
https://github.com/jython/jython/blob/4f68d98f34fd6165058944640925b0d1370caf4f/src/org/python/core/AbstractDict.java#L262

I've just compiled 2.7.1 with the command `ant` and I don't get this failure. (Ant is version 1.10.12.) I have no Mac to test on. I wonder if it is something to do with paths, or defaults in the version of Ant in use?
