### ISSUE TITLE
PySystemStateTest fails in master branch

### ISSUE THREAD

**Issue by datavisortedyu** [jython/jython#247]
I encountered the following test failure in master branch as of commit ad164ef3163d38591b79ee4ce4dd367779d0541f
```
  <testcase classname="org.python.core.PySystemStateTest" name="testGetJarFileNameFromURL_jboss" time="0.003">
    <failure message="expected:&lt;vfszip:/some[%20]dir/some.jar/org/pyt...&gt; but was:&lt;vfszip:/some[ ]dir/some.jar/org/pyt...&gt;" type="junit.framework.ComparisonFailure">junit.framework.ComparisonFailure: expected:&lt;vfszip:/some[%20]dir/some.jar/org/pyt...&gt; but was:&lt;vfszip:/some[ ]dir/some.jar/org/pyt...&gt;
        at org.python.core.PySystemStateTest.testGetJarFileNameFromURL_jboss(PySystemStateTest.java:158)
```
Here is my environment:
```
Darwin Zhihongs-MacBook-Pro-2.local 22.3.0 Darwin Kernel Version 22.3.0: Thu Jan  5 20:50:36 PST 2023; root:xnu-8792.81.2~2/RELEASE_ARM64_T6020 arm64
```
Java:
```
java version "1.8.0_202"
Java(TM) SE Runtime Environment (build 1.8.0_202-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.202-b08, mixed mode)
```

**Comment by jeff5** [comment]
I think we can safely say https://github.com/jython/jython/commit/ad164ef3163d38591b79ee4ce4dd367779d0541f is not the cause.

I don't have a Mac personally but we can try this on the GitHub CI.

**Comment by jeff5** [comment]
I can't reproduce this fault with the current latest versions of Java 8 and macOS on the GitHub CI.
The `javatest` target runs without errors in a similar configuration:
https://github.com/jython/jython/actions/runs/6685660383/job/18164186964?pr=283#step:7:146

The apparent failing test just checks that our understanding of the `java.net.URL` constructor is correct. The reported line number in the issue is off by one from the line number I get when I simulate the error.
https://github.com/jython/jython/actions/runs/6690623737/job/18176284271?pr=283#step:7:139

This all makes me think the test result is not valid. It made me improve the tests, however.
