### ISSUE TITLE
Build fails when using java module

### ISSUE THREAD

**Issue by unknowIfGuestInDream** [jython/jython#288]
When I use jython-standalone in the java module, some packages in jython will conflict with my existing packages with the same name, for example:
org.w3c.dom.html

![image](https://github.com/jython/jython/assets/57802425/8cd1319e-a221-41b6-82c9-e386a1f9e32a)
![image](https://github.com/jython/jython/assets/57802425/9651f7a4-8aca-47ad-8986-895a5cee2141)

# ENV
- OS: Windows 11
- JDK: Temurin-17.0.8.1
- Jython: jython-standalone-2.7.3
- Build tool: Maven-3.9.5

# Others
![image](https://github.com/jython/jython/assets/57802425/8d3a5afc-a535-4848-8140-add75bc32c5d)
![image](https://github.com/jython/jython/assets/57802425/fc2f1fdf-6792-48fd-b107-1843dec43231)

**Comment by jeff5** [comment]
You can post text more usably by quoting it in Markdown.

I'm afraid Jython 2.x is designed without any consideration for the Java module system. It's quite old, you see. 

The package `org.w3c.dom.html` in `jython-standalone` comes from the bundling of the `xercesImpl-2.12.2.jar`. When we bundle it, we rename everything from the `org.apache` package, but it also contains one interface class `org.w3c.dom.html.HTMLDOMImplementation`. But that is duplicated in the JDK `rt.jar`, so I don't know why. History, perhaps.

I think it would be harmless to exclude it when we build the JAR. (Obviously this statement needs testing.)

You write "*some* packages in jython will conflict". It would help us to have a full list.

I dislike this bundling we do, although I know the stand-alone JAR is convenient to many. As you appear to be applying a proper dependency management scheme, would citing `jython-slim` as a dependency work for you?

**Comment by unknowIfGuestInDream** [comment]
Thank you for your answer, now it looks good after using `jython-slim`.
So now when users need to reference jython in their projects, they should reference `jython-slim` instead of `jython-standalone`? If so, I may have submitted a wrong issue.

**Comment by jeff5** [comment]
> ... I may have submitted a wrong issue.

No, I think your issue is valid against the stand-alone version, thanks for pointing it out.

I think the stand-alone is probably right where a user just wants a Python interpreter they can run from Java, but it has some problems (like JARs going out of date). In a project that is able to manage its own dependencies, you can avoid those problems by using the slim JAR, which contains only our own work (including the PSF's).

OTOH dependency management is hard, so when I recommend the slim JAR I'm always interested in whether it worked at all (thanks for saying it did) and whether we did our part as well as we might (e.g. did we force you into versions you didn't want or bloat you didn't need).

**Comment by jeff5** [comment]
Leaving open so we remember to fix as suggested in https://github.com/jython/jython/issues/288#issuecomment-1826762459.
