### ISSUE TITLE
Code Style

### ISSUE THREAD

**Issue by appt2** [jython/jython#297]
hi how to format code Python? like in vs code

**Comment by jeff5** [comment]
I use Eclipse with the PyDev plug-in and it just works. I've had to pin it to Eclipse 2022-09 and pydev-9.3 because Jython is still at v2.7 of the language. I haven't tried VSCode on it.

Very little in Jython has a different grammar from Python 2.7. Only really that attribute names exposed from Java potentially clash with Python keywords. The one that commonly arises is when you want to refer to `System.in`.

Is this what you mean?

**Comment by jeff5** [comment]
If you just want general help with Python in an IDE, [Python Help](https://discuss.python.org/c/users/7) is a good place to ask (but they will not want to answer anything specific to 2.7).

**Comment by appt2** [comment]
> اگر فقط در یک IDE کمک کلی در مورد Python می‌خواهید، [Python Help](https://discuss.python.org/c/users/7) مکان خوبی برای پرسیدن است (اما آنها نمی‌خواهند به چیزی خاص به 2.7 پاسخ دهند).

Hello, I just want to organize the Python code

**Comment by jeff5** [comment]
Seems like you have to install an extension. https://code.visualstudio.com/docs/python/formatting

Not really a Jython issue.
