### ISSUE TITLE
What is the recommended way to return values from multiline scripts?

### ISSUE THREAD

**Issue by alturkovic** [jython/jython#359]
I have this simple example written in Kotlin:
```kotlin
fun main() {
    val justReturnScript = PythonInterpreter().use {
        it.compile("""
            input
        """.trimIndent())
    }

    val printThenReturnScript = PythonInterpreter().use {
        it.compile("""
            print(input)
            input
        """.trimIndent())
    }

    PythonInterpreter().use {
        it["input"] = mutableMapOf("a" to 1)

        println("1:" + it.eval(justReturnScript))
        println("2:" + it.eval(printThenReturnScript))
    }
}
```
The output of this `main` is:
```
1:{u'a': 1}
{u'a': 1}
2:None
```

I would expect this to be:
```
1:{u'a': 1}
{u'a': 1}
2:{u'a': 1}
```

What is the recommended way to return values from multiline scripts?

**Comment by Stewori** [comment]
Hi, I am not aware that we have an official recommendation on this matter. What I can tell you is that I personally use [`PythonInterpreter.get`](https://apidia.net/java/Jython/2.7.4/?pck=org.python.util&cls=.PythonInterpreter#get-java.lang.String-) to retrieve the variable of interest, in your case (I'm writing in Java)
```
return it.get("input");
```

That said, I agree that your observation appears counter intuitive, but have to point out that it is documented/specified behavior:
The API documentation of [`compile`](https://apidia.net/java/Jython/2.7.4/?pck=org.python.util&cls=.PythonInterpreter#compile-java.lang.String-) states:

> Compiles a string of Python source as either an expression (if possible) or a module.

Apparently, a multiline program becomes a module, while for a single line it is possible to turn it into an expression, which is ultimately done then. An expression has a different return semantics than a module which doesn't have a return value.

That may appear strange, but it is Python semantics. Functions, methods and expressions have return values, modules don't. Multiline code does not qualify as an expression, so it has to become a module.
That leads me to point out one more option: You could turn the code into a function. That would require a corresponding declaration in your Python script (unless you want to deal with the [`PyFunction` constructors](https://apidia.net/java/Jython/2.7.4/?pck=org.python.core&cls=.PyFunction#sum:constructor); `input` would be passed among globals):

```
def f():
    print(input)
    return input
```
(input being a module variable in this case, which you can set as you did before; alternatively you may make it an arg of `f`.)

Then you retrieve `f` as a `PyObject` via `it.get("f")` and I *think* the resulting object can be cast into a [`PyFunction`](https://apidia.net/java/Jython/2.7.4/?pck=org.python.core&cls=.PyFunction), which you can evaluate using [`__call__`](https://apidia.net/java/Jython/2.7.4/?pck=org.python.core&cls=.PyFunction#__call__-]). However, you would not need to cast, because you can execute [`__call__`](https://apidia.net/java/Jython/2.7.4/?pck=org.python.core&cls=.PyObject#__call__-) readily for a generic `PyObject`.

Disclaimer: I did not test this right now. There may be subtleties.

**Comment by yogi1967** [comment]
eval is for stuff like "1+2", not multi running of code - hence the None is the result of print() returning nothing (or it's possibly a module as per previous comment). 
exec is for running code and multi line (with security concerns)...

I work with Python and py scripts a lot... I know this is an example, but I wouldn't be working this way IMHO... What are you trying to achieve overall?

**Comment by yogi1967** [comment]
_(sorry @Stewori - crossed in the ether)_

**Comment by yogi1967** [comment]
Example:

```
pi = something.getPythonInterpreter()
input={"a": 1}

x=pi.compile("""
def xxx():
 print "**", input;
 return input
""")

pi.set("input", input)
print "2:",pi.get("input")
pi.eval(x)
print "3:",pi.get("xxx")()
```

Result:
```
2: {'a': 1}
3: ** {'a': 1}
{'a': 1}
```

**Comment by alturkovic** [comment]
Okay got it, thank you @Stewori  and @yogi1967!

I went with 2 different approaches that I need, one for transform actions, and another for filtering actions. The examples are a bit more complex, but I just wanted to leave them as a reference in case someone else encounters a similar problem...

```kotlin
class PythonTransformer(
    script: String,
    private val variableName: String = "json"
) : JsonTransformer {
    private val compiledScript = PythonInterpreter().compile(script)

    override fun transform(json: JsonNode): JsonNode = PythonInterpreter().use {
        it[variableName] = mapper.convertValue<Any?>(json)
        it.exec(compiledScript)
        convertToJson(it[variableName])
    }
    
    private fun convertToJson(pyResult: PyObject) : JsonNode {
        val any = pyResult.__tojava__(Any::class.java)
        return mapper.valueToTree(any)
    }
}
```

```kotlin
class PythonFilter(
    script: String,
    private val variableName: String = "json",
    private val functionName: String = "accept"
) : JsonFilter {
    private val compiledScript = PythonInterpreter().compile(script)

    override fun accept(json: JsonNode): Boolean = PythonInterpreter().use {
        it[variableName] = mapper.convertValue<Any?>(json)
        when (val result = it.eval(compiledScript)) {
            is PyNone -> when (val function = it[functionName]) {
                null -> false // the result of a single-line filtering call is None and there is no "accept" function defined
                else -> function.__call__().__nonzero__()
            }
            else -> result.__nonzero__()
        }
    }
}
```

This way, I can write mutating transformations in multiline scripts. I can also write simple filter evaluations as a single line script, but also execute them as functions if single-line does not cover it.

This is good enough for my needs, thanks for the explanations again!

**Comment by yogi1967** [comment]
Nice use of Kotlin!

I also had cause to use this recently:

`pyResult.__tojava__(Any::class.java)`

took me a while to work out tho' !! 😉
