### ISSUE TITLE
Does jython have a security configuration

### ISSUE THREAD

**Issue by wangyu-2024** [jython/jython#61]
Does jython have a sandbox function to restrict access to java classes and os modules when running the code

**Comment by Stewori** [comment]
No, not Jython itself. However, you can use security features of the JVM, i.e. Java security managers.
Sandboxing on Python level is kind of considered impossible: [this article](https://lwn.net/Articles/574215/) states

> To build a secure sandbox, the whole Python process must be put in an external sandbox.

And with Jython you have just that, in form of the JVM. (Infamously, the JVM has its own history of security holes but that's a different story.)

**Comment by sar009** [comment]
Disclaimer before I start I don't know the internal working of Jython much or for that matter any python distribution.
I was wondering if we can create a jar without `os`, `http.client` module etc, `eval` function basically all interface that interacts with os or network. Or an option to disable these modules while creating `ScriptEngine`.

**Comment by Stewori** [comment]
Take a look at the article I linked above. It shows where the approach of restricting functionality leads. Python is so rich that there are "always" subtle ways to work around the restrictions. It won't be safe until you put a wall around the entire Python realm, e.g. Java security managers (if that can be considered "safe"). Also, I suspect removing the modules you named would require non-trivial fixes due to cross dependencies, probably already to build properly.
