### ISSUE TITLE
ImportError: cannot import name PyShadowString

### ISSUE THREAD

**Issue by pcolmer** [jython/jython#67]
I've installed Jython 2.7.2 (on Ubuntu 18.04) but, when I try to run a script that imports `os`, I get this error:

```
Traceback (most recent call last):
  line 10, in <module>
  File "/usr/local/lib/jython/Lib/os.py", line 27, in <module>
    from org.python.core import PyShadowString
ImportError: cannot import name PyShadowString
```

I cannot find `PyShadowString` anywhere on my system, particularly not within `/usr/local/lib/jython/Lib`.

Have I missed out a step required for the installation to complete or have I got a configuration error somewhere?

**Comment by Stewori** [comment]
Something must be wrong with the jar file. PyShadowString is written in Java and should be in jython.jar, not in the Lib folder. Maybe some older jython.jar is used (by accident) because some path is pointing wrongly? PyShadowString did not yet exist in Jython 2.7.0 or earlier. For further diagnosis, more info on the launch command and the build process would be needed.

**Comment by pcolmer** [comment]
@Stewori Thank you for explaining how PyShadowString is implemented. That has cleared up the whole situation.

(I'm using a separate tool that embeds Jython but requires the separate installation of Jython if Python libraries are needed, and the embedded version is *very* old now. I need to chase those developers)

My apologies for the noise.
