### ISSUE TITLE
It is not clear what is "Jython Software License" referred in LICENSE.txt concerning zxJDBC. Needs fix?

### ISSUE THREAD

**Issue by mikavuo** [jython/jython#74]
Hi,

This is copied from the LICENSE.txt file:
"The zxJDBC package was written by Brian Zimmer and originally licensed
under the GNU Public License.  The package is now covered by the **Jython
Software License**".

I did not find the **Jython Software License** in the LICENSE.txt or with Google search. Maybe it is something that needs to be fixed. It would be also nice if the license information would be included in the zxJDBC.jar component. Now the license scanners report missing license. 

Regards, Mika

**Comment by mikavuo** [comment]
Hello everyone

More details.

in https://github.com/jython/jython/blob/master/README.md it is said: "See ACKNOWLEDGMENTS for details about Jython's copyright, **license**, contributors, and mailing lists." and yes, there it is: "These
components are licensed, like Jython itself, under the Python Software Foundation License version 2 from the Python Software Foundation." (lines 51-53).  That is pretty clear, but https://github.com/jython/jython/blob/master/LICENSE.txt file seems to tell a different story: it lists three different licenses:
"A. TERMS AND CONDITIONS FOR ACCESSING OR OTHERWISE USING JYTHON"
- PYTHON SOFTWARE FOUNDATION LICENSE VERSION 2
- Jython 2.0, 2.1 License
- JPython 1.1.x Software License.

I'd like to believe that it is the Python Software Foundation License version 2 , but there seems to be conflicting infromation in the **LICENSE.**txt file. If expecting to take a look at the license, then choosing between files named README.md and LICENSE.txt would definitely take me to take a look at the LICENSE.txt and I would expect to find the license there.

**Comment by jeff5** [comment]
For at least a decade (I just mean since before I joined the project), contributors have agreed to the Python Software Foundation Contributor Agreement, that is, contributions to Jython are made to the PSF, and the PSF makes them freely available to all on its own terms. You can apply whatever license you like to your own work as long as you grant this to the PSF.  Jython (then JPython) was a non-PSF project before 2005-ish.

AFAICT the "Jython Software License" is that license under which Jython is a PSF property made available for your use.

Currently, contributor status involves also creating an account on the CPython bug-tracker, but I can't see @bzimmer in there. To the extent [this commit](https://github.com/jython/jython/commit/5a9d4a2aa8894b9836a07faa6414d69aeaa8b733#diff-d0ed4cc3fb70489fe51c7e0ac180cba2a7472124f9f9e9ae67b01a37fbd580b7R18-R20) was made by the author of that package himself, I'd say there was good evidence zxJDBC is covered by it. There seems no reason to doubt that zxJDBC is usable as part of Jython on the terms of that same file.

The fact that we (and CPython) have a sequence of licenses is confusing to me. I understand this is because previous versions, of which later ones are derived works, were released under different terms. But as I am not a lawyer, I sometimes wonder exactly what the implications are.

**Comment by bzimmer** [comment]
Hi Jeff,

I'm happy to comply with the contributor agreement, I honestly have no idea
if I have done so in the past. Is this form
<https://www.python.org/psf/contrib/contrib-form/> the best way to make
zxJDBC's contribution official?

thanks, brian

**Comment by jeff5** [comment]
Hello Brian:

Thanks for your contribution of zxJDBC.

That looks like it. Note that one of the questions is your [bugs.python.org](https://bugs.python.org/) user name, so if you don't have one, you'd have to make an account there.

If you can be bothered, it would save the problem coming up again. Also, you'd be all set to contribute to CPython, should the mood strike you. :)

Jeff

**Comment by bzimmer** [comment]
Hi Jeff,

I submitted my contributor agreement. My username, which appears to have existed, is 'bzimmer'. Let me know if there's anything needed. Thanks!

thanks, brian

**Comment by jeff5** [comment]
Ok, I must've missed you in the list, but now it knows your GitHub name [this app can check the CLA](https://check-python-cla.herokuapp.com/). No show yet, but it takes a human to process it.

Thanks so much. Hopefully this eliminates any future uncertainty.

**Comment by mikavuo** [comment]
Thanks, Jeff and Brian!

**Comment by bzimmer** [comment]
I just confirmed my contributor agreement via the [app](https://check-python-cla.herokuapp.com/). I think we're good to go!

thanks, brian
