### ISSUE TITLE
Python 3.7+ Support

### ISSUE THREAD

**Issue by timkofu** [jython/jython#95]
Hi,

Are there plans to support Python 3.7+?

**Comment by jeff5** [comment]
Yes, but not with dates. I intend to implement a [Jython 3.8](https://www.jython.org/jython-3-mvp). It's why I'm somewhat negligent of 2.7 and its bugs.

**Comment by CyberFlameGO** [comment]
[jython/jython:main](https://github.com/jython/jython/tree/main) is the development branch for it

**Comment by jeff5** [comment]
Yes, but there's nothing on it as I'm considering off-repo how to start.

**Comment by Pomax** [comment]
What kind of timeline are we talking about though? Because python 2.7 officially hit EOL a year and a half ago, and the syntax differences are big enough that anyone writing Python code that is valid today won't be able to run that on a 2.7-compatible interpreter.

It's kind of past time to actually start releasing Jython3 versions (even if they're beta) =S

What can others do to help you get to a release? Because I'm sure everyone in the Jython community would prefer having a 3 available as soon as possible (even if it's a beta), now that everything's either removed, or is actively removing, 2.7 support.

**Comment by CyberFlameGO** [comment]
Yeah I've been waiting for it too, I agree

**Comment by Stewori** [comment]
I suspect a "me too" sequence may not be the thing that actually moves Jython 3 forward. If someone wonders what may be better suited, these earlier posts on the topic might give an idea: https://github.com/jython/jython3/issues/36#issuecomment-369408773, https://github.com/jython/jython/issues/24#issuecomment-670022103

(Edit: sorry, I was kind of in a bad mood when I wrote the lines above. Of course it's great to hear that many people desire Jython 3! Even if it's not moving forward as quickly as we would whish.)

**Comment by timkofu** [comment]
> Yes, but not with dates. I intend to implement a Jython 3.8. It's why I'm somewhat negligent of 2.7 and its bugs.

Okay, we'll be patient, and thank you for the hard work.
